name: angry_raphi
description: "AngryRaphi - Person rating app with raphcons"
publish_to: 'none'

version: 2.3.1+6

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  
  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  
  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.5.0
  
  # Network & Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.5
  
  # UI & UX
  lottie: ^3.1.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Navigation
  go_router: ^14.6.2
  
  # Web
  flutter_web_plugins:
    sdk: flutter
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # AI
  google_generative_ai: ^0.4.6
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  injectable_generator: ^2.5.0
  build_runner: ^2.4.13
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/data/
    - assets/whatsnew.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
